
# Build the direwolf binaries

FROM registry.fedoraproject.org/fedora-minimal:latest as builder

RUN microdnf -y install git gcc gcc-c++ make alsa-lib-devel \
                libudev-devel avahi-devel cmake3 alsa-utils \
                python3.12 python3-pip python3-devel

RUN git clone --depth 1 https://github.com/wb2osz/direwolf.git/ && \
    cd direwolf && \
    mkdir build && cd build && \
    cmake .. && \
    make -j4 && \
    make DESTDIR=/target install


# COPY . $HOME/src/chatfx/
# WORKDIR $HOME/src/chatfx/
# RUN python3 -m pip install .
RUN python3 -m venv /app
ENV PATH=/app/bin:$PATH
RUN python3 -m pip install git+https://github.com/cidrblock/chatfx.git

# Build the final image

FROM registry.fedoraproject.org/fedora-minimal:latest
COPY --from=builder /target/usr/local/bin /usr/local/bin
COPY --from=builder /target/etc/udev/rules.d/99-direwolf-cmedia.rules /etc/udev/rules.d/99-direwolf-cmedia.rules
COPY --from=builder /app /app

RUN microdnf -y install python3.12 alsa-lib avahi-libs && \
    microdnf clean all

ENV PATH=/app/bin:$PATH
ENV DIREWOLF_PARAMS="-d x2o -t 0 -q d -c /etc/direwolf.conf"
ENV CHATFX_PARAMS="-s /etc/chatfx.toml"
ENV TERM=xterm-256color

CMD nohup /usr/local/bin/direwolf ${DIREWOLF_PARAMS} &> direwolf.log & chatfx ${CHATFX_PARAMS}
