name: publish
on: [push]
jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the hello-docker Docker image
        run: |
          docker build /home/runner/work/chatfx/chatfx --tag ghcr.io/cidrblock/chatfx:latest
          docker push ghcr.io/cidrblock/chatfx:latest
